### ISSUE TITLE
Module (ZF\Oauth2\Doctrine) could not be initialized.

### ISSUE THREAD

**Issue by inbaz** [API-Skeletons/zf-oauth2-doctrine#78]
Hi,

I'm not able to load this module. Can you give some advice what to look at to get this running? I went through the documentation and did the following changes:
* I copied config/oauth2.doctrine-orm.global.php.dist and changed the entity to use Application\Entity\User
* I added the zf-mvc-auth config into zf-mvc-auth-oauth2-override.global.php it gets returned in an array
* I added 'storage' => 'oauth2.doctrineadapter.default', in my oauth2.global.php
* doctrine is setup to be connected to a database and without ZF\Oauth2\Doctrine loaded I'm able to get orm:info and can create the structure.

Once ZF\Oauth2\Doctrine is enabled the app simply doesn't start with the message: Module (ZF\Oauth2\Doctrine) could not be initialized.
I was not able to follow the error until the depth where the real error happens. Can you tell me where I can look at or where to check what's wrong to get this module running?

Cheers
Andi

**Comment by TomHAnderson** [comment]
The module name is `ZF\OAuth2\Doctrine`  Start with that case error.

**Comment by inbaz** [comment]
Checked that, so I have 'ZF\OAuth2\Doctrine', in place in my module.config.php.

**Comment by TomHAnderson** [comment]
The error you are seeing is from the Module Manager.  I find putting debug statements in the Module.php file the best way to show if it's loading at all.

**Comment by sergiohermes** [comment]
The problem occurs because at installation time it does not automatically add `'ZF\OAuth2\Doctrine'`, in its global **module.config.php**  file.

So far so, and I believe to be correct, as it generates some dependent modules that support this adapter. For this to initialize it must satisfy the dependencies these exceptions exist, and in addition to the module being injected, the .dist extension files of the module config folder, must be placed in   **config/autoload** . As described in the documentation.

[See the documentation](http://doctrine-in-apigility-docs.readthedocs.io/en/latest/zf-oauth2-doctrine/application%20configuration.html#installation)

Mistakes are our best friends.

I hope I have helped.

**Comment by TomHAnderson** [comment]
Fixed with 10e87ff9d6f338dfe279ead22a41de27363cf52b
